# Generated by Django 4.2.6 on 2023-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_bio_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_bio_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
